server:
  port: 8081
spring:
  application:
    name: rocket-mq
rocketmq:
  name-server: 121.43.41.19:9876
  producer:
    #生产者组
    group: self-producer-group
  consumer:
    group: self-consumer-group