server:
  port: 8081
spring:
  application:
    name: rocket-mq
rocketmq:
  name-server: 60.167.177.183:9876
  producer:
    #生产者组
    group: self-producer-group
  consumer:
    group: self-consumer-group
    pull-batch-size: 10
