server:
  port: 8096
  servlet:
    context-path: /mongo
spring:
  application:
    name: MONGO-DB
  data:
    mongodb:
      host: 47.99.70.125
      port: 27017
      username: mongoadmin
      password: mongoadmin
      database: test
      authentication-database: admin

logging:
  level:
    log4j.category.org.springframework.data.mongodb: debug