server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store_orders?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: 127.0.0.1
    password: 7rWBBtyi2H3Cc9ld
    port: 6379
    lettuce:
      pool:
        max-wait: -1ms
    timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        format_sql: true
  statemachine:
    data:
      jpa:
        repositories:
          enable: false
